download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "e_pwr_consump.zip", method="curl")
unzip("e_pwr_consump.zip")
pwrdata <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?")
pwrdata$datetime <- strptime(paste(pwrdata$Date, pwrdata$Time), "%d/%m/%Y %H:%M:%S")
sub <- subset(pwrdata, datetime >= as.POSIXlt("2007-02-01") & datetime <= as.POSIXlt("2007-02-02 23:59:59"))
png("plot2.png")
plot(sub$datetime, sub$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.off()