download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "e_pwr_consump.zip", method="curl")
unzip("e_pwr_consump.zip")
pwrdata <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?")
pwrdata$datetime <- strptime(paste(pwrdata$Date, pwrdata$Time), "%d/%m/%Y %H:%M:%S")
sub <- subset(pwrdata, datetime >= as.POSIXlt("2007-02-01") & datetime <= as.POSIXlt("2007-02-02 23:59:59"))
png("plot4.png")
par(mfrow=c(2,2))
plot(sub$datetime, sub$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab="")
plot(sub$datetime, sub$Voltage, type="l", ylab="Voltage", xlab="datetime")
plot(sub$datetime, sub$Sub_metering_1, ylab="Energy sub metering", xlab="", type="l")
points(sub$datetime, sub$Sub_metering_2, type="l", col="red")
points(sub$datetime, sub$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
plot(sub$datetime, sub$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime")
dev.off()